name: tasked
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  cloud_firestore: ^6.1.1
  cupertino_icons: ^1.0.8
  easy_date_timeline: ^2.0.9
  firebase_auth: ^6.1.4
  firebase_core: ^4.3.0
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.1
  flutter_slidable: ^4.0.3
  google_fonts: ^6.2.1
  provider: ^6.1.5+1

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/splash/

flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#000000"

  image: assets/images/splash/splash_light.png
  image_dark: assets/images/splash/splash_dark.png

  android: true
  ios: true
