// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-kmlUqlVOoclDpmgCmYAfDIDSB0nIWSc',
    appId: '1:695720855434:web:05978f247673c53ba66a73',
    messagingSenderId: '695720855434',
    projectId: 'tasked-flutter-app',
    authDomain: 'tasked-flutter-app.firebaseapp.com',
    storageBucket: 'tasked-flutter-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-OQicVAm4pKb1bxVoPqKDa9Aie-vtZU0',
    appId: '1:695720855434:android:f38e7df136ecd51ca66a73',
    messagingSenderId: '695720855434',
    projectId: 'tasked-flutter-app',
    storageBucket: 'tasked-flutter-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZ4i4Z6WuIfz3DQV2gEGpxXnqzHBLb1JE',
    appId: '1:695720855434:ios:b4d74c8ab464f886a66a73',
    messagingSenderId: '695720855434',
    projectId: 'tasked-flutter-app',
    storageBucket: 'tasked-flutter-app.firebasestorage.app',
    iosBundleId: 'com.example.tasked',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZ4i4Z6WuIfz3DQV2gEGpxXnqzHBLb1JE',
    appId: '1:695720855434:ios:b4d74c8ab464f886a66a73',
    messagingSenderId: '695720855434',
    projectId: 'tasked-flutter-app',
    storageBucket: 'tasked-flutter-app.firebasestorage.app',
    iosBundleId: 'com.example.tasked',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-kmlUqlVOoclDpmgCmYAfDIDSB0nIWSc',
    appId: '1:695720855434:web:d12654c2ff2f5f06a66a73',
    messagingSenderId: '695720855434',
    projectId: 'tasked-flutter-app',
    authDomain: 'tasked-flutter-app.firebaseapp.com',
    storageBucket: 'tasked-flutter-app.firebasestorage.app',
  );
}
